[package]
name = "qollage"
version = "0.1.0"
authors = ["HQS Quantum Simulations <info@quantumsimulations.de>"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.56"
categories = ["science", "simulation"]
readme = "README.md"
repository = "https://github.com/HQSquantumsimulations/qollage"
description = "Typst interface for roqoqo Rust quantum computing toolkit by HQS Quantum Simulations"
include = ["src*", "LICENSE", "README.md"]

[lib]
name = "qollage"
path = "src/lib.rs"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qoqo = { version = "1.12", default-features = false, features = [] }
roqoqo = { version = "1.12", features = ["serialize"] }
roqollage = { version = "0.1", path = "../roqollage" }
image = "0.24"

[dependencies.pyo3]
version = "0.21"
features = ["num-complex"]

[dev-dependencies]
test-case = "3.0"
qoqo_calculator = "1.2"
ndarray = "0.15"

[build-dependencies]
pyo3-build-config = "0.21"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
